# 我是最大的标题

## 我是老二

### 我是三级

#### 所有的符号都是英文符号

In [1]:
from contextlib import nullcontext
from ctypes import pythonapi
import numpy  as np
import pandas as pd

from numpy.f2py.f2py2e import numpy_version

#代码包一般会有一个文件README.md 目的是提供代码项目的大致介绍，这个文件的0后缀一般是.md
#要在文字里插入代码，就用反引号来包裹住代码
#NumPy经常被用于科学及工程领域 NumPy里最核心的数据结构就是ND array n维数组
#相似之处是都可以通过索引来获取元素 print(arr[0]) 打印第一个元素
#for element in arr: print(element) 打印所有元素 print(arr[0:3]) 打印前三个元素 可以通过切片获得某范围的多个元素
#NumPy数组里的元素得是一个类型的，数据类型需要统一，比如全是数字，列表里的数据类型不需要统一
#对NumPy数组进行大规模数学运算或其它操作时，执行速度远高于Python的内置列表，因此效率是数据处理方面选择NumPy的首要原因
#创建一维数组
arr1 = np.array([1,2,3])
#创建二维数组
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
#数组对象有一些属性 ndim会返回给我们数组的维度 shape会返回一个元组，表示各个维度的元素的个数 size返回数组里面的元素总个数,int开头说明类型是整数，64表示的比特长度
print(arr1.ndim) ;print(arr2.ndim)
print(arr1.shape);print(arr2.shape)
print(arr1.size);print(arr2.size)
print(arr1.dtype);print(arr2.dtype)
#除了array方法手动传入元素值创建数组，numpy也提供了其它一些创造数组的方法
arr3 = np.zeros(3); print(arr3)
arr4 = np.ones(5); print(arr4)  #数字后面有点是因为这些数字的类型是浮点数
arr5 = np.arange(5,10,2); print(arr5)  #起始值 结束值 步长
arr5   #交互式环境，不需要print语句
arr_even = np.arange(10,21,2); print(arr_even)
list1 = np.array([4,8,49,7,4441,1])
sorted_list1 = sorted(list1); print(sorted_list1)
sorted_list1 = list1.sort(); print(list1)
#numpy的sort函数 与numpy的sort方法
print(list1[-1])
print(list1[0:3])
print(list1[(list1 > 6)&(list1<100)])   #广播机制，产生的结果就是布尔值数组，每个布尔值都代表了这个数字是否大于6
#布尔值可以用来对形状相同的数组进行索引
s1 = pd.Series([5,17,3,26,36])
s1 #索引和元素同时展示 元素种类一并展示


[[1 2 3]
 [4 5 6]]
1
2
(3,)
(2, 3)
3
6
int64
int64
[0. 0. 0.]
[1. 1. 1. 1. 1.]
[5 7 9]
[10 12 14 16 18 20]
[np.int64(1), np.int64(4), np.int64(7), np.int64(8), np.int64(49), np.int64(4441)]
[   1    4    7    8   49 4441]
4441
[1 4 7]
[ 7  8 49]


0     5
1    17
2     3
3    26
4    36
dtype: int64

In [ ]:
import pandas as pd
s_id = pd.Series(["01","02","03","04","05"])
s_class = pd.Series(["二班","一班","二班","三班","一班"])
s_grade = pd.Series([92,67,70,88,76])
df1 = pd.DataFrame({"学生":s_id,"班级":s_class,"成绩":s_grade})

df4 = pd.DataFrame({"学生":{"小明":"01","小红":"02","小杰":"03","小丽":"04","小华":"05"},
                    "班级":{"小明":"二班","小红":"一班","小杰":"二班","小丽":"三班","小华":"一班"},
                    "成绩":{"小明":92,"小红":67,"小杰":70,"小丽":88,"小华":76}})
print(df1.index);
print(df4.index)
df4.columns
df4.values    #返回的类型是NumPy数组  所有针对NumPy数组的操作都可以用在values上了
df4.T  #行列转置
df4['成绩']   #列的类型是Series  跟Python字典后面放上方括号 键名，就可以把值提取出来一样
df4.成绩;df4.班级   #每列Series是DataFrame的属性 如果列名有特殊符号就不能通过属性来获取了
df4[["学生","成绩"]]     #方括号里放入列表，列表里传入多个列名  返回是个DataFrame 因为结果由多个Series组成
#提取列用列名   提取行用索引   从Series里提取元素  我们推荐用loc和iloc 一个根据标签索引 一个根据位置索引
#DataFrame也可以用iloc去提取想要的行
df4.loc["小丽"];df4.iloc[3]
df4.loc["小红":"小丽"];df4.iloc[1:3]   #位置索引做切片是不包含结束值的，所以这里执行有差异
df4.loc[["小红","小杰"]]   #可以通过列表提取任一行   loc还可以提取某个表格数据
df4.iloc[2,0]   #表示行列
df4.loc["小红":"小杰","班级":"成绩"]
df4.iloc[1:3,1:3]
df4.loc[:,"班级":"成绩"]
df4.iloc[:,1:3]   #:表示全部范围的索引

df4.iloc[[1,3],0:2]
df4.loc[["小红","小丽"],"学生":"班级"]
# 一般每一行代表一个实例  比如一个城市  一个学生 而每一列代表数据实例的属性 比如说城市的人口 学生的身高
#删选行相当于是从已有的数据里提取符合条件的实例  更加常见和合理的

df4[df4.成绩>80]   #DataFrame的列是Series类型  Series和条件结合起来会返回一个布尔值的Series 长度和DataFrame的行数相对应
#因此DataFrame就是在根据这个布尔值Series来保留True对应的行
df4[(df4["成绩"]>80) & (df4["成绩"]<90)]
df4.head(5)



In [ ]:
import pandas as pd
name = pd.Series(["小陈","小李","小王","小张","小赵","小周"],index=["001","002","003","004","005","006"])
name
gender = pd.Series(["女","女","男","男","女","男"],index=["006","005","004","003","002","001"])
gender
height = pd.Series([172.5,168.0,178.2,181.3,161.7],index=["001","002","003","004","005"])
height
students = pd.DataFrame({"姓名":name,"性别":gender,"身高":height})
students   #会根据index去对齐所有的
students.T   #T不是方法，不需要加括号
#之前在学series的时候学过一个apply方法，然后把函数运用在每一个元素上，从而得到一个新的series，DataFrame也有一个
# 同名方法，参数接收一个函数，调用后就会将其运用在DataFrame的每列或每行上，不指定axis时默认是对列进行操作，
# 传给apply的函数会被运用在，我们可以把每一列看作是传入函数里的参数，
students=students.drop(["姓名"],axis=1)
def trim_mean(data):
    if not pd.api.types.is_numeric_dtype(data):
        return None
    else:
        data_len = len(data)
        data_sum = data.sum()
        max_num = data.max()
        min_num = data.min()
    return (data_sum-max_num-min_num)/(data_len - 2)

pjz=students.apply(trim_mean)  #指定axis=1每行数据就会成为参数

#传给applymap的函数会被运用在每一个元素上
students=students.drop(["性别"],axis=1)
#students.applymap(lambda x: x+5)
plz=students.map(lambda x: x+5)
plz=plz.describe()   #得到的是各列的统计信息   describe方法会自动忽略掉所有的非数字列
plz


In [ ]:
import pandas as pd

students = pd.DataFrame({"姓名":{"001":"小陈","002":"小李","003":"小王","004":"小张","005":"小赵","006":"小周"},
                         "考试1":{"001":85,"002":91,"003":86,"004":79,"005":96,"006":81},
                         "考试2":{"001":95,"002":92,"003":81,"004":89,"005":91,"006":89},
                         "考试3":{"001":92,"002":94,"003":89,"004":95,"005":91,"006":92}
})

average = students.loc[:,"考试1":"考试3"].mean(axis=1)   #loc是根据标签，标签索引是包含结束值的  loc是属性而不是方法或者函数
name = students["姓名"]
student_average = pd.DataFrame([name,average])
student_average1 = pd.DataFrame({"姓名":name,"分数":average})
students.loc[:,"考试1":"考试3"].apply(lambda x:x.sort_values().iloc[-2])
students.loc[:,"考试1":"考试3"].astype('int').describe()
#students.describe()

#爬虫主要做的事情就是 通过发送请求获取网页源代码 解析网页源代码内容 提取出想要的内容
#不要爬取公民隐私内容 不要爬取著作权保护的内容 不要爬取国家事务国防建设 尖端科学技术领域的计算机系统等
#通过直接下载 有网和网址即可  API  Application Programming Interface 应用程序编程接口
#API定义了两个程序之间的服务合约 即双方是如何请求和响应来进行通讯的
#爬虫获取的是网页源码 网页源码本身是用来给浏览器进行渲染的，而不是直接的信息，所以需要解析，如果网站直接提供给我们API，我们就能直
#直接按照对方规定好的服务合约根据规则发送请求，直接获取想要的数据，不需要经过解析源码这一步
#获取到数据后一般会把数据存储为某种格式，以供后续读取或修改 比如CSV JSON等
# 更改后缀不影响实际的文件格式 后缀会影响电脑选择哪个应用程序来打开它
# JavaScript Object Notation 意思是JavaScript对象表示方法 与python的列表或字典有类似之处
#JSON对象可以转为python字典  JSON数组可以转为Python列表
#区别 python字典可以用整数等不可变数据类型作为键，json里面只能是字符串作为键，不能是其它类型
#而且字符串必须被双引号包围
#本质是Js的对象 所以布尔值是小写开头，支持嵌套就可以支持复杂的数据格式
#"star"  31 true 数组  ["age",7]   对象{"age":25}   null相当于None
#json对象的键是不能存在重复的，因为值要靠键提取，键重复了就不知要提取的是哪个值了

#体积小，很轻易的转为其它语言所需的数据结构 pandas库有一个pd.read_json函数
pd.read_json("./cell_phone.json")   #直接把json转成DataFrame 完成文件读取  json解析 转成DataFrame的全流程
#不用pandas的话每一步都需要一段单独的代码


In [ ]:
#每列是一个变量，每行是一个观察值，每个单元格是一个值，任何不符合以上三点的都是乱数据 结构问题
#如果每列是一个观察值，每行是一个变量，需要行列转置  如果每列是多个变量，就要进行拆分列，甚至进行重塑
#按其实际含义拆分进行命名
#如果每行是多个观察值，就要进行拆分行，让数据粒度更细，同时冗余了部分信息，甚至进行重塑，确保每行只包含一个观察值
#清理前的数据是宽数据，清理后的数据是长数据，清理后的目的是让程序能够高效的处理数据，而不是方便人类理解
#所以你会觉得清理前的宽数据反而更直观易懂
####丢失数据处理方法####
#处理空缺数据需要具体问题具体分析，如果你知道缺失值的实际值，可以更新表格数据，人工填充
#丢失值不影响计算的情况下可以不处理丢失值，pandas会自动忽略缺失值，
#如果是关键变量的缺失值可以把该行数据删除，只留下对分析结果有意义的数据
#比如你想分析年龄，而年龄值正好缺失，那该条数据无意义，也可以把平均数，中位数，众数填充进去
#####重复数据#####
#找到数据，直接删除
#格式问题导致的重复数据，进行替换去重
#无效数据  替换删除
#拆分列，重塑行，删除缺失值，删除重复数据，对数据类型进行转换
######重命名索引和列名#####
df1.rename(index={"2_":"2","_5":"5"})    #index参数指定为一个字典,老的名字作为键，新索引作为值，就会得到一个新的DataFrame
df1.rename(columns={})    #columns指定为一个字典，老列名作为键，新列名作为值，为了让改变生效，我们可以重新赋值
df1.rename(columns={},inplace=True)    #就不用重新赋值了

In [ ]:
df1.sample(10)
series("").isnull().sum()
df1.rename(columns=str.upper,inplace=True)  #inplace表示原地修改df
df1.set_index("lm")    df1.reset_index()  #原本索引变为单独一列

In [ ]:
"20玩/m³".split("/") #返回一个列表
#series的str属性会返回一个包含很多方法的类实例，比如包含upper split
df1[["rk","mj"]]=df1["少高"].str.split("/",expend=True)
df1.drop("sg",axis=1)
df1["x"].str().cat(df1["m"],sep="-")
pd.melt(df1,id_vars=["国家代码","年龄"],var_name="年龄组",value_name="病例数")
df1.explode("")
df1.loc["003","xse"]=800
df1.loc["001":"003","xse"]=800   #都需要自己定位缺失值的位置
df1["b"].fillna(df1["b"].mean())
df4.fillna({"S":0,"b":""})
df4.dropna(subset=["工资"],axis=1)    #删除包含空缺值的行
df4.drop_duplicates(subset=["xm","sg"],keep="last")
replace_dict={"qh":"qhdx"}
df1.replace(replace_dict,inplace=True)



# D:\BaiduNetdiskDownload
#评估和清理电商销售数据
#原始数据集记录了一家英国在线零售公司在2010年12月1日至2011年12月9日期间的所有交易情况，涵盖了该公司在全球不同国家和地区的
#业务数据。该公司主要销售覆盖各个场景的礼品，包括但不限于生日礼品、结婚纪念品，圣诞礼品等等该公司的客群主要包括批发商和个人消费者
#其中批发商占据了相当大的比例
#数据每列含义如下
#InvoiceNo:发票号码，6位数，作为交易的唯一标识符，如果这个代码以字母c开头，表示这笔交易被取消
#StockCode：产品代码，5位数，作为产品的唯一标识符
#Description：产品名称
#Quantity：产品在交易中的数量
#InvoiceDate：发票日期和时间。交易发生的日期和时间
#UnitePrice：单价  价格单位为英镑
#CustomerID：客户编号，5位数，作为客户的唯一标识符
#Country：国家名称。客户所在的国家名称

## 读取数据


















In [2]:
import pandas as pd

In [4]:
original_data=pd.read_csv("D:/BaiduNetdiskDownload/e_commerce.csv")

In [5]:
original_data.head()

InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

      InvoiceDate  UnitPrice  CustomerID         Country  
0  12/1/2010 8:26       2.55     17850.0  United Kingdom  
1  12/1/2010 8:26       3.39     17850.0  United Kingdom  
2  12/1/2010 8:26       2.75     17850.0  United Kingdom  
3  12/1/2010 8:26       3.39     17850.0  United Kingdom  
4  12/1/2010 8:26       3.39     17850.0  United Kingdom

## 评估数据

### 评估数据整齐度

In [7]:
original_data.sample(10) #从抽样的10行数据来看，数据符合每列是一个变量 每行是一个观察值 每个单元格是一个值  列 行 格
#具体来说每行是关于某商品的一次交易 每列是交易相关的各个变量，因此不存在结构性问题

InvoiceNo StockCode                         Description  Quantity  \
503322    578922     23582        VINTAGE DOILY JUMBO BAG RED          3   
326466    565541     21650      ASSORTED TUTTI FRUTTI BRACELET         6   
403206    571554    84029E      RED WOOLLY HOTTIE WHITE HEART.         7   
181349    552466     22028        PENNY FARTHING BIRTHDAY CARD        12   
225719    556731    85123A  WHITE HANGING HEART T-LIGHT HOLDER         6   
212143    555413     21559   STRAWBERRY LUNCH BOX WITH CUTLERY         3   
508211    579196     22597      MUSICAL ZINC HEART DECORATION          2   
458518    575842     22575        METAL MERRY CHRISTMAS WREATH         6   
484382    577531     22668                   PINK BABY BUNTING         1   
82392     543201     22518            CHILDS GARDEN BRUSH BLUE         1   

             InvoiceDate  UnitPrice  CustomerID         Country  
503322  11/27/2011 12:00       2.08     17236.0  United Kingdom  
326466    9/5/2011 12:00       0.19     14159.0  United Kingdom  
403206   10/18/2011 9:13       9.13         NaN  United Kingdom  
181349    5/9/2011 15:21       0.42     13458.0  United Kingdom  
225719   6/14/2011 11:41       2.95     18283.0  United Kingdom  
212143     6/3/2011 9:50       2.55     17994.0  United Kingdom  
508211  11/28/2011 15:54       1.63     14096.0  United Kingdom  
458518  11/11/2011 12:01       1.95     15024.0  United Kingdom  
484382  11/20/2011 13:58       5.79         NaN  United Kingdom  
82392     2/4/2011 13:03       4.13         NaN  United Kingdom

### 评估数据干净度

In [8]:
original_data.info() #从输出结果来看，数据共有541909条观察值，而Description、CustomerID变量存在缺失值，此外InvoiceDate的数据类型应为日期，CustomerID的数据类型应为字符串，应当进行数据格式转换
#脏数据可能存在的问题包括缺失数据 重复数据 不一致数据 无效数据或错误数据等

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   InvoiceNo    541909 non-null  object 
 1   StockCode    541909 non-null  object 
 2   Description  540455 non-null  object 
 3   Quantity     541909 non-null  int64  
 4   InvoiceDate  541909 non-null  object 
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object 
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB


#### 评估缺失数据

InvoiceNo StockCode Description  Quantity      InvoiceDate  UnitPrice  \
622       536414     22139         NaN        56  12/1/2010 11:52        0.0   
1970      536545     21134         NaN         1  12/1/2010 14:32        0.0   
1971      536546     22145         NaN         1  12/1/2010 14:33        0.0   
1972      536547     37509         NaN         1  12/1/2010 14:33        0.0   
1987      536549    85226A         NaN         1  12/1/2010 14:34        0.0   
...          ...       ...         ...       ...              ...        ...   
535322    581199     84581         NaN        -2  12/7/2011 18:26        0.0   
535326    581203     23406         NaN        15  12/7/2011 18:31        0.0   
535332    581209     21620         NaN         6  12/7/2011 18:35        0.0   
536981    581234     72817         NaN        27  12/8/2011 10:33        0.0   
538554    581408     85175         NaN        20  12/8/2011 14:06        0.0   

        CustomerID         Country  
622            NaN  United Kingdom  
1970           NaN  United Kingdom  
1971           NaN  United Kingdom  
1972           NaN  United Kingdom  
1987           NaN  United Kingdom  
...            ...             ...  
535322         NaN  United Kingdom  
535326         NaN  United Kingdom  
535332         NaN  United Kingdom  
536981         NaN  United Kingdom  
538554         NaN  United Kingdom  

[1454 rows x 8 columns]

In [11]:
original_data[(original_data["Description"].isnull()) & (original_data["UnitPrice"] != 0)]
#分析目标是根据市场销售数据，挖掘畅销产品，以便制定更有效的市场策略来提升营收，所以以上数据无法提供有效含义，不具备价值可以删除
original_data[original_data["CustomerID"].isnull()]   #不是分析畅销产品的必要变量，并且从输出结果来看CustomerID缺失的交易数据仍然有效
#因此保留该变量为空的观察值
#了解本次数据分析的目的是什么，从分析目的出发才能更好的判断数据评估和清理的方向

InvoiceNo StockCode                      Description  Quantity  \
622       536414     22139                              NaN        56   
1443      536544     21773  DECORATIVE ROSE BATHROOM BOTTLE         1   
1444      536544     21774  DECORATIVE CATS BATHROOM BOTTLE         2   
1445      536544     21786               POLKADOT RAIN HAT          4   
1446      536544     21787            RAIN PONCHO RETROSPOT         2   
...          ...       ...                              ...       ...   
541536    581498    85099B          JUMBO BAG RED RETROSPOT         5   
541537    581498    85099C   JUMBO  BAG BAROQUE BLACK WHITE         4   
541538    581498     85150    LADIES & GENTLEMEN METAL SIGN         1   
541539    581498     85174                S/4 CACTI CANDLES         1   
541540    581498       DOT                   DOTCOM POSTAGE         1   

            InvoiceDate  UnitPrice  CustomerID         Country  
622     12/1/2010 11:52       0.00         NaN  United Kingdom  
1443    12/1/2010 14:32       2.51         NaN  United Kingdom  
1444    12/1/2010 14:32       2.51         NaN  United Kingdom  
1445    12/1/2010 14:32       0.85         NaN  United Kingdom  
1446    12/1/2010 14:32       1.66         NaN  United Kingdom  
...                 ...        ...         ...             ...  
541536  12/9/2011 10:26       4.13         NaN  United Kingdom  
541537  12/9/2011 10:26       4.13         NaN  United Kingdom  
541538  12/9/2011 10:26       4.96         NaN  United Kingdom  
541539  12/9/2011 10:26      10.79         NaN  United Kingdom  
541540  12/9/2011 10:26    1714.17         NaN  United Kingdom  

[135080 rows x 8 columns]

#### 评估重复数据

In [ ]:
#哪些变量是不应该重复的
#虽然InvoiceNo StockCode CustomerID都是唯一标识符，但一次交易可以包含多件商品，所以InvoiceNo可以存在重复，不同交易也可以包含同种商品，因此StockCode也是可以重复的，因为一个客户可以下单多个商品，因此CustomerID也可以存在重复，那么针对此数据集我们无需评估重复数据

#### 评估不一致数据

In [12]:
#不同字符串指代同一个国家的情况
original_data["Country"].value_counts()  #从Country变量来看，"USA"、“United States” 均在表示美国，因此这些值在清洗步骤对这些值进行统一
#只保留一个指代值

Country
United Kingdom          495266
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
China                      288
Singapore                  229
USA                        218
UK                         211
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United States               73
United Arab Emirates        68


#### 评估无效或错误数据

In [14]:
#可以通过DataFrame的describe方法，对数值统计信息进行快速了解
original_data.describe() #从输出结果来看，Quantity和UnitPrice存在负数，会对后续数值分析产生影响，因此我们先筛选出Quantity数值为负数的观察值
#进一步评估其含义


Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [22]:
original_data[original_data["Quantity"] < 0]
original_data[(original_data["Quantity"] < 0) & (original_data["InvoiceNo"].str[0] !="C") & (original_data["UnitPrice"] != 0)]

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

## 清理数据
根据前面分析得到的结论，我们需要进行数据清理包括。
把InvoiceDate的数据类型转为日期格式。
把CustmoID变量的数据类型转换为字符串。
#把Description变量缺失的观察值删除。
#把Country变量值USA替换为Unit States UK替换为Unit Kingdom。
#把Quantity变量为负数的观察值删除。
#把UnitPrice变量值为负数的观察值删除。

In [40]:
cleaned_data = original_data.copy()
cleaned_data.head()
cleaned_data["InvoiceDate"]=pd.to_datetime(cleaned_data["InvoiceDate"])
cleaned_data["InvoiceDate"]   #datetime64 64表示所占用的长度
cleaned_data["CustomerID"]=cleaned_data["CustomerID"].astype(str).str.slice(0,-2)
cleaned_data["CustomerID"]
cleaned_data.dropna(subset=["Description"],inplace=True)
print(cleaned_data["Description"].isnull().sum())
cleaned_data["Country"]=cleaned_data["Country"].replace({"USA":"United States","UK":"United Kingdom","U.K.":"United Kingdom"})
print(len(cleaned_data[(cleaned_data["Country"] == "USA") | (cleaned_data["Country"] == "UK")]))
#保存清理后的数据

0
0


## 保存清理后的数据

In [42]:
cleaned_data.to_csv("D:/BaiduNetdiskDownload/e_commerce_cleaned.csv",index=False) #会默认把DataFrame的索引保存成一列